import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_components/Navbar";

export const metadata: Metadata = {
  title:
    "BRImo - Aplikasi Mobile Banking BRI - Bank BRI - Melayani Dengan Sepenuh Hati",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html style={{ padding: 0 }} lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
